[Interface]
PrivateKey = $FREE_TURN_WG_CLIENT_PRIVATE_KEY
Address = $FREE_TURN_WG_CLIENT_ADDRESS/32
DNS = $FREE_TURN_WG_DNS
MTU = 1280

[Peer]
PublicKey = $FREE_TURN_WG_SERVER_PUBLIC_KEY
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = $FREE_TURN_WG_CLIENT_ENDPOINT
PersistentKeepalive = 25
